cabal-version:      3.0
name:               Hike

-- The package version.
-- See the Haskell package versioning policy (PVP) for standards
-- guiding when and how versions should be incremented.
-- https://pvp.haskell.org
-- PVP summary:     +-+------- breaking API changes
--                  | | +----- non-breaking API additions
--                  | | | +--- code changes with no API change
version:            0.1.0.0

synopsis: Travel Planner
description: Travel Planner
license:            AGPL-3.0-or-later
license-file:       LICENSE
-- author:
-- maintainer:
-- copyright:
category:           Web
build-type:         Simple

-- Extra doc files to be distributed with the package, such as a CHANGELOG or a README.
extra-doc-files:    CHANGELOG.md

-- extra-source-files:


common Dependencies
    build-depends: base
                 , bytestring
                 , text
                 , directory
                 , time
                 , base-compat
                 , mtl
                 , aeson
                 , attoparsec
                 , string-conversions
                 , lucid
                 , http-media
                 , http-types
                 , blaze-html
                 , blaze-markup
                 , wai
                 , warp
                 , servant ^>= 0.20.3.0
                 , servant-server
                 , servant-js
                 , servant-auth
                 , servant-auth-server
                 , persistent
                 , persistent-sqlite
                 , esqueleto
                 , monad-logger
                 , conduit
                 -- The following packages are mostly for dev, should remove when production
                 , wai-cors
                 , servant-options

library Models
    import: Dependencies

    ghc-options: -Wall -threaded -ddump-splices -ddump-tc -ddump-ds-preopt -ddump-to-file

    build-depends:

    hs-source-dirs: App

    exposed-modules: Model
                   , Model.Enum

    default-language: GHC2021

library Authentications

    import: Dependencies

    ghc-options: -Wall

    build-depends: Models

    hs-source-dirs: App

    exposed-modules: Auth

    other-modules: Model
                 , Model.Enum

    default-language: GHC2021

library Handlers
    import: Dependencies

    ghc-options: -Wall

    build-depends: Models, Authentications

    hs-source-dirs: App

    exposed-modules: API
                   , API.Handlers
                   , API.Handlers.User
                   , API.Handlers.Trip
                   , API.Handlers.Membership
                   , API.Handlers.Place
                   , API.Handlers.Internal
                   , Auth

    other-modules: Model
                 , Model.Enum

    default-language: GHC2021

executable Hike
    import:           Dependencies

    ghc-options: -Wall -threaded

    main-is:          Main.hs

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:

    build-depends: Models
                 , Handlers
                 , Authentications

    other-modules: API
                 , API.Handlers
                 , API.Handlers.Place
                 , API.Handlers.Trip
                 , API.Handlers.User
                 , API.Handlers.Itinerary
                 , API.Handlers.Membership
                 , API.Handlers.Internal
                 , Auth
                 , Model
                 , Model.Enum
                 , WarpApp
                 , ServantApp
                 , Seed
                 , Config

    hs-source-dirs: App

    default-language: GHC2021

executable JS
    import:           Dependencies

    ghc-options: -Wall -threaded

    main-is:          Main.hs

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:

    build-depends: Models
                 , Handlers

    other-modules: API
                 , API.Handlers
                 , API.Handlers.Place
                 , API.Handlers.Trip
                 , API.Handlers.User
                 , API.Handlers.Itinerary
                 , API.Handlers.Membership
                 , API.Handlers.Internal
                 , Model
                 , Model.Enum

    hs-source-dirs: JS
                  , App

    default-language: GHC2021
