:PROPERTIES:
:ID:       bcb80cca-24ee-4613-93f8-a480dbccccad
:END:
#+TITLE: Password Storage

* High-level Overview

We try to follow exsiting standard for password storage. To me, this meant following the [[https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html][OWASP cheat sheet]] [fn:1] for best practices. 

The sign up logic is roughly as follow:
1. User request sign up
2. Generate a random salt
3. Compute hash of password + salt using /Argon2id/
4. Store plain salt, hashed password into the database along with other user information

The sign in logic is roughly as follow:
1. User request sign in with unique identifier and password
2. Look up user based on the unique identifier in database
3. Retrieve plain salt and hashed password (call the latter ~target~) 
4. Compute the hash of sign in password + salt (call the result ~hashedPassword~)
5. Check ~hashedPassword == target~.

* Implementation Details

** Library

We use [[https://hackage-content.haskell.org/package/crypton][~crypton~]] [fn:2] and [[https://hackage-content.haskell.org/package/text][~text~]] [fn:3]for most of the functionality. 

The collections of imports are listed below:
- [[https://hackage-content.haskell.org/package/text-2.1.4/docs/Data-Text-Encoding.html][~Data.Text.Encoding~]] :: Provides ~encodeUtf8~ to convert user password in ~Text~ into ~ByteString~.
- [[https://hackage-content.haskell.org/package/crypton-1.1.4/docs/Crypto-Error.html][~Crypto.Error~]] :: Provide the ~CryptoFailable~ datatype which may be inspected to determine if hashing function ran successfully.
- [[https://hackage-content.haskell.org/package/crypton-1.1.4/docs/Crypto-Random.html][~Crypto.Random~]] :: Provides the ~MonadRandom~ class with the ~getRandomBytes~ function to generate random salt.
- [[https://hackage-content.haskell.org/package/crypton-1.1.4/docs/Crypto-KDF-Argon2.html][~Crypto.KDF.Argon2~]] :: Provides the configuration and implementation of the Argon2 algorithm.

** Computation Context

To generate a random salt, we use the ~getRandomBytes~ function from the ~MonadRandom~ class.

The library only provides two implemenations of the ~MonadRandom~ class, one of which is ~(MonadRandom IO)~. Because we need to perform salt generation and hashing in a handler, this means we perform salt, hashing in the ~IO~ monad, then lift the computation into a ~Handler~ monad.

** ByteString-like Class and Types

#+begin_src
  class (..., ByteArrayAccess ba) => (ByteArray ba) where
  ...

  instance ByteArray ByteString where
  ...
#+end_src

~getRandomBytes~ returns a type that is an instance of ~ByteArray~. Because we need to store the randomly generated salt in database, and ~persistent~ only supports ~ByteString~, that is the type that is going to be used (after type inference and constraint solving).


** Hashing

The hashing function ~hash~ is provided by the ~Crypto.KDF.Argon2~ module:
#+begin_src haskell
  hash ::
    (ByteArrayAccess password, ByteArrayAccess salt, ByteArray out)
    => Options -> password -> salt -> Int -> CryptoFailable out
  --                                   ^
  --                                   |
  --                           Hash output length
#+end_src

- ~Options~ :: Hash algorithm configuration.
- ~password, salt~ :: Self explanatory.
- ~Int~ :: Hash out length.
- ~(CryptoFailable out)~ :: The hash may fail.

There exists [[https://hackage.haskell.org/package/cryptonite-0.30/docs/src/Crypto.KDF.Argon2.html#defaultOptions][a default option]] provided by the library:
#+begin_src haskell
  defaultOptions :: Options
  defaultOptions =
      Options
          { iterations = 1
          , memory = 2 ^ (17 :: Int) -- in KiB, 2 ^ 17 KiB = 128 MiB
          , parallelism = 4
          , variant = Argon2i
          , version = Version13
          }
#+end_src

We can override the options using the normal Haskell record syntax.
- Change variant to ~Argon2id~.
- 128 MiB memory is greater than the recommended 19 MiB.
- Rest should be fine.

** ~CryptoFailable a~

A type similar to ~(Either e)~, specialized for possible crypto errors.

* Footnotes

[fn:1] OWASP Cheat Sheet Series, [[https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html][Password Storage Cheat Sheet]]

[fn:2] ~crypton~ Hackage, [[https://hackage.haskell.org/package/crypton][~crypton~: Cryptography Primitives sink]]

[fn:3] ~text~ Hackage, [[https://hackage-content.haskell.org/package/text][~text~: An efficient packed Unicode text type.]]
