#+TITLE: Defining APIs

* Main Flow

Serving an endpoint takes 3 steps:
1. Defining an ~API~ endpoint
2. Defining a ~Server~ for the said ~API~
3. Serve the ~Server API~, creating an /wai/ ~Application~

** API

In the ~servant~ framework, APIs are defined as types [fn:1].

** Server

Suppose we have an API defined, where the response type is expected to be ~Entity~. A simple handler for the said API will have the type ~(Handler Entity)~. 
~(Handler a)~ is shorthand for ~(ExceptT Server Error IO a)~. To paraphrase the ~servant~ tutorial, ~Handler~ is the simplest monad that allows for 3 things:
1. Return result on success,
2. Return error on failure,
3. Perform IO. [fn:2]

Correspondingly, we have the following properties:
1. ~Handler~ monad get access to ~return~ on success.
2. ~Handler~ is an instance of ~MonadError~, giving us access to ~throwError~.
3. ~Handler~ is an instance of ~MonadIO~, giving us access to ~liftIO~.

There are cases that the type of the Handler is not ~(Handler a)~. This is because the type of the function ~serve~ (see below) that constructs the application requires the handler to be of type ~(Server api)~. We explain the ~Server~ type constructor in [[./The_Server_Type.org][a different section]].

** Application

Given a pair of matching API and Server, we can create an ~wai~ application with the ~serve~ function.

* Database Access

When working with an API that needs access to the database, we can pass the database connection as an argument.

How the connection is used depends on the interface provided by other libraries. Currently, the project uses ~persistent~ for database connection. In this framework, we can use the provided ~runSqlPool~ function:

#+begin_src haskell
  handler :: ConnectionPool -> Server API
  handler pool = liftIO $
    let action = do
          rows :: [Entity MyData] <- selectList [] [] -- A database operation
          return $ map entityVal rows
    in runSqlPool action pool
#+end_src

When using ~runSqlPool~, it is important to note the monad of the action performed by ~runSqlPool~ has to be an instance of ~MonadUnliftIO~. Because ~Handler~ is not an instance of ~MonadUnliftIO~, we are forced to perform only "simple IO actions" for the database action, then ~liftIO~ the result of ~runSqlPool~ into a ~Handler~ monad.

* Footnotes

[fn:1] ~servant~ tutorial: [[https://docs.servant.dev/en/latest/tutorial/ApiType.html][A web API as a type]]

[fn:2] ~servant~ tutorial: [[https://docs.servant.dev/en/latest/tutorial/Server.html#the-handler-monad][Serving an API - The ~Handler~ monad]]
