:PROPERTIES:
:ID:       9680f30f-f25c-400d-a46d-1b11053c9e3a
:END:
#+TITLE: The ~Server~ Type
#+BIBLIOGRAPHY: "../Ref.bib"

The ~Server~ type is type constructor provided by the ~servant~ library. It is used pervasively through out the tutorial and cookbook. In this documentation, we dive into the details of the ~Server~ type.

* Motivating Example

Consider the following snippet, adapted from the ~servant~ tutorial [fn:1].

#+begin_src haskell
  type MyAPI = Get '[JSON] Int

  myServer :: Server MyAPI
  myServer = return 42
#+end_src

Depending on how the LSP chooses to resolve types, one may found the type of ~(return 42)~ to be ~(Handler Int)~. This is not syntactically the same as the ~(Server MyAPI)~ type annotation. Furthermore, tutorial [fn:1] also says "for each endpoint, your handlers will by default run in the ~Handler~ monad".

This results in the following question:
#+begin_quote
How can a computation in the ~Handler~ monad be typechecked against a ~Server~ type?
#+end_quote

We resolve the apparent inconsistency in the following documentation.

* Type Families and Associated Data Types
:PROPERTIES:
:ID:       3ac949dc-90c5-4430-a821-d50dde67b09a
:END:

#+begin_center
tl;dr: ~Server~ is a type level function, and ~(Server MyAPI)~ evaluates to ~(Handler Int)~
#+end_center

In the ~servant~ source code [fn:2], you can find the following class definition and type alias:

#+begin_src haskell
  class HasServer api context where
    type ServerT api (m :: Type -> Type) :: Type
    ...

  type Server api = ServerT api Handler
#+end_src

** ~ServerT~

~ServerT~ is an example of /Type Families/ in Haskell [fn:3], in particular, it is an example of /Associated Data Types/ [cite:@10.1145/1047659.1040306].

~ServerT~ is a /type level function/. It takes types as arguments, and returns a type as the output. Recall APIs are represented as types, and different APIs may satisfy the ~HasServer~ constraint in different ways. Consequently, ~ServerT~ will behave differently on different APIs. 

** ~Server~

The last line states ~(Server api)~ is a /type synonym/ [fn:4]. Thus the ~(Server MyAPI)~ becomes ~(ServerT MyAPI Handler)~, which becomes ~(ServerT (Get '[JSON] Int) Handler)~ by synonym again.

* Resolving Motivating Example:

We return to the motivating example

** Resolving ~MyAPI~ to normal form.

From the source code, [fn:5] [fn:6], we notice ~Get~ is a type synonym:
#+begin_src haskell
  type Get = Verb 'GET 200
#+end_src

Thus, we have:
#+begin_src haskell
  Get '[JSON] Int = Verb 'Get 200 '[JSON] Int
#+end_src

** Image of ~ServerT~ on ~Verb~

There is an ~HasServer~ instance associated with ~Verb~ [fn:7]:

#+begin_src haskell
  instance {-# OVERLAPPABLE #-} ( ... ) -- some preconditions omitted
    => HasServer (Verb method status ctypes a) context where
    
    type ServerT (Verb method status ctypes a) m = m a
#+end_src

** Evaluating ~(Server MyAPI)~

Combining with the type synonyms we have from before, we have the following type equalities:

#+begin_src haskell
  Server MyAPI
  = ServerT MyAPI Handler
  = ServerT (Get '[JSON] Int) Handler
  = ServerT (Verb 'Get 200 '[JSON] Int) Handler
  = Handler Int -- By the ServerT definition
#+end_src

** Conclusion

This explains why the tutorial says we need to supply a ~Server~ type with a ~Handler~ type implementation.

Notice, the case from the tutorial was simple. As we seen, if the API is more complicated (for example contains ~QueryParam~), then the type of the handler we need to produce may also be more complicated (for example a function type to account for the param string).

* Appendix: Other Combinators

In ~servant~, API are represented as types, and constructed using type constructors (or "combinators"). Two such constructors are:
- ~QueryParam~ :: Represents an API with a query string parameter, and
- ~:>~ :: Sequencing combinators.

With that knowledge, consider the following ~HasServer~ instance from the ~servant~ source code:
#+begin_src haskell
  instance ( ... HasServer api context ... ) -- Some preconditions omitted
    => HasServer (QueryParam' mods sym a :> api) context where

    type ServerT (QueryParam' mods sym a :> api) m =
      RequestArgument mods a -> ServerT api m
#+end_src

- In the precondition, we have ~(HasServer api context)~, requiring the type level function to be defined for the tail portion of the API. 
- In the body of the class instance, we see when ~ServerT~ is applied to an API of the shape ~((QueryParam' mods sym a) :> api)~, it constructs a function, where:
  - The input type is ~(RequestArgument mods a)~, and
  - The output type is the result of applying the type level function ~ServerT~ to ~api~ and ~m~ (Which we know exists by the precondition).

* Footnotes

[fn:1] ~servant~ tutorial: [[https://docs.servant.dev/en/latest/tutorial/Server.html#a-first-example][Serving an API - A first example]]

[fn:2] ~servant~ source code: [[https://hackage-content.haskell.org/package/servant-server-0.20.3.0/docs/src/Servant.Server.Internal.html#HasServer][~Servant.Server~ ~HasServer~]]

[fn:3] GHC Documentation: [[https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/type_families.html][6.4.10 Language extensions, Types, Type Families]]

[fn:4] HaskellWiki: [[https://wiki.haskell.org/Type_synonym][Type Synonym]]

[fn:5] ~servant~ source code: [[https://hackage-content.haskell.org/package/servant-0.20.3.0/docs/src/Servant.API.Verbs.html#Get][~Servant.API.Verb Get~]]

[fn:6] ~servant~ source code: [[https://hackage-content.haskell.org/package/servant-0.20.3.0/docs/src/Servant.API.Verbs.html#Verb][Servant.API.Verb Verb]]

[fn:7] ~servant~ source code: [[https://hackage-content.haskell.org/package/servant-server-0.20.3.0/docs/src/Servant.Server.Internal.html#line-319][~HasServer~ for a HTTP verb]]
